Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Posterunkowy', 630, 'pilnowanie porz¹dku na ulicy, pielêgnowanie kwiatów na ulicach, jedzenie p¹czków, gro¿enie œmierci¹')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Starszy posterunkowy', 680, 'suszenie suszark¹ z³ych kierowców, pouczanie posterunkowego jak powinien groziæ œmierci¹, jedzenie darmowego jedzenia podanego przez centralê magicznej policji')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Przodownik', 750, 'suszenie suszark¹ z³ych kierowców, zgarnianie podejrzanych osobników do pojazdu milicyjnego, picie kawy')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Starszy przodownik', 790, 'picie kawy, pouczanie ni¿szych rang¹, odbieranie magicznych wiadomoœci, siedzenie na posterunku i uk³adanie pasjansa')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Aspirant', 830, 'umiejêtne udawanie zapracowania, zamykanie siê we w³asnym gabinecie na ca³y dzieñ i siedzenie na obrotowym krzeœle')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Podkomisarz', 860, 'chodzenie pomiêdzy ni¿szymi rang¹ i narzekanie na ich pracê, narzekanie na bol¹ce plecy, ogólnie narzekanie')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Komisarz', 900, 'ktoœ jednak musi coœ robiæ… wystawianie karnych kartek na wieczornych patrolach')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Nadkomisarz', 910, 'musi robiæ wszystko, ¿eby pokazaæ komisarzowi, ¿e jest nad nim, narzekaæ na zbyt du¿¹ iloœæ pracy i brak snu, wystawianie karnych kartek w godzinach porannych')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Podinspektor', 930, 'musi siê przypodobaæ Nadinspektorowi, robiæ mu kawê, przynosiæ ciastka, narzekaæ na inspektora')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Inspektor', 940, 'musi drêczyæ podinspektora, bo jest lizusem, zazdroœciæ Nadinspektorowi')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Nadinspektor', 1000, 'byæ zawsze zmêczonym i poddenerwowanym, krzyczeæ na Inspektora')
Insert into Stanowiska(Nazwa, Pensja, Zakres_obowiazkow) 
values ('Naczelnik', 1500, 'Grzegorz Dmitr¹ba jest w ca³oœci oddany dobru ojczyzny i Patrycjusza Wiekiegonosa')